name: rtd-tutorial
channels:
  - defaults
dependencies:
  # core dependencies
  - python=3.9.7
  - sphinx=4.4.0
  - sphinx_rtd_theme=0.4.3
  - docutils=0.16

  # sub-dependencies
  - alabaster=0.7.12
  - babel=2.9.1
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=4.8.2
  - jinja2=3.0.2
  - markupsafe=2.0.1
  - openssl=1.1.1m
  - packaging=21.3
  - pip=21.2.4
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - pytz=2021.3
  - requests=2.27.1
  - setuptools=58.0.4
  - snowballstemmer=2.2.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.37.2
  - tzdata=2021e
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zipp=3.7.0
